CREATE TABLE IF NOT EXISTS guilds (
    id TEXT NOT NULL PRIMARY KEY UNIQUE,
    name TEXT,
    icon TEXT,
    owner TEXT,
    log_channel TEXT,
    welcome_channel TEXT,
    welcome_message TEXT ,
    leave_channel TEXT,
    leave_message TEXT ,
    toggle_welcome BOOLEAN ,
    toggle_leave BOOLEAN ,
    toggle_log BOOLEAN ,
    mass_mentions BOOLEAN ,
    mass_mentions_count INTEGER ,
    mass_mentions_time INTEGER ,
    mass_mentions_action TEXT ,
    toggle_mentions BOOLEAN ,
    toggle_links BOOLEAN ,
    toggle_invites BOOLEAN ,
    toggle_nsfw BOOLEAN ,
    tolerance INTEGER  DEFAULT -5,
    toggle_ai INTEGER DEFAULT 0 
);